[package]
name = "sysy-analyzer-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.45.0", features = ["full"] }
tower-lsp = "0.20.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
